server:
  port: 8085

spring:
  datasource:
    password: raje1409
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=2
  rabbitmq:
    host: rabbit
    port: 5672
    username: rajesh
    password: rajesh
    virtualHost: /

info:
  component: ApiGateway
  artifact: api-gateway
  version: 5.0.0
  