server:
  port: 8085

jwt:
  secret: secretkey
  token:
    validity: 86400000
    
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedMethods: "*"
              allowedHeaders: "*"    
  rabbitmq:
    host: localhost
    port: 5672
    username: rajesh
    password: rajesh
    virtualHost: /

info:
  component: Gateway
  artifact: gateway
  version: 5.0.0
  