server:
  port: 8085

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: rajesh
    password: rajesh
    virtualHost: /

info:
  component: Gateway
  artifact: gateway
  version: 5.0.0
  