server:
  port: 9091

spring:
  datasource:
    password: raje1409
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  rabbitmq:
    host: rabbit
    port: 5672
    username: rajesh
    password: rajesh
    virtualHost: /            

info:
  component: UserService
  artifact: user-service
  version: 5.0.0